version: '3.7'

services:
  db:
    image: postgres:11-alpine
    container_name: node_example
    ports:
      - 5432:5432
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - ./provision/sql:/docker-entrypoint-initdb.d/
      - node-example-data:/var/lib/postgresql/data

volumes:
  node-example-data:


